# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbaba169d3d746af92efce83f3955a88c45be039011b76cb5d1606da0528545d5b68bb2b6338ab9a2a2279d3152095e17dc02de67728e0f0e567ee8d10e60b2e

test:
  secret_key_base: 88e7690a9c8b0a4cc93e01e3b5e1974715a0b794ce39340afb9096a070d15b7664f1347dd2246c82ae57c9ee2c4f38740f308adcda8378780219fe337fcc8d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
