# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 836b75ae459aa72360d15ddc6767a70764ada8766e0272ce8429efe53d702ab4165e6c8bb71ca80e9a048f5c0552ab35909a31ca33315296b605d2dd0a2cfdcb

test:
  secret_key_base: de7ce0f8c75698e33a67720a10f6fb54acc501e4859f5916a55afa2d1efd48439394653226094cca6d293e1f91883efe58718b00a232046b0a4f40f396f1aef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
