# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a949df7ebfada5573ce4601f519975bfd58e8adb53ece2bad04d7950cdef3d56188d2831e10afcbacf12323a2826ea1d49738a5ebfb322e2c9e646c9559f684

test:
  secret_key_base: 41f79780aa8a67c2b4578ac1a8435c10f8b4b3e4ed776ecc678b8c8f2522a2ec1db3f5907e26aa793dac36da0138c494317cda96fd6058501a8b06ee9df8a606

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
